# Generated by Django 5.2.4 on 2025-07-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_registration_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('pizza', 'Pizza'), ('chicken', 'Chicken'), ('drinks', 'Drinks'), ('fruits', 'Fruits'), ('momo', 'Momo'), ('roti', 'Roti'), ('others', 'Others'), ('khana_set', 'Khana Set'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='others', max_length=30)),
                ('image', models.ImageField(upload_to='seller/items')),
                ('is_available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('kitchen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='seller_registration_data.sellerregistrationform')),
            ],
        ),
    ]
