# Generated by Django 5.2.4 on 2025-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kitchen_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller/kitchen_photos'),
        ),
        migrations.AddField(
            model_name='item',
            name='preperiation_time',
            field=models.DecimalField(decimal_places=0, default=20, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='available_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
