# Generated by Django 5.2.4 on 2025-08-07 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0002_item_kitchen_photo_item_preperiation_time_and_more'),
        ('seller_registration_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('CANCEL', 'Cancel'), ('SUCESS', 'Sucess')], default='PENDING', max_length=20)),
                ('deleveryStatus', models.CharField(choices=[('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'OutForDelivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PREPARING', max_length=20)),
                ('paymentStatus', models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'online')], default='COD')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deliveryAddress', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Status_updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ImageField(blank=True, null=True, upload_to='payment')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('items_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_items', to='seller.item')),
                ('kitchen_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='seller_registration_data.sellerregistrationform')),
            ],
        ),
    ]
