# Generated by Django 5.2.4 on 2025-08-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone_number'),
        ('seller', '0002_item_kitchen_photo_item_preperiation_time_and_more'),
        ('seller_registration_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_items', to='seller.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kitchen_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='seller_registration_data.sellerregistrationform'),
        ),
    ]
