# Generated by Django 5.2.4 on 2025-08-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_buyer_name_alter_order_items_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleveryStatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'OutForDelivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
