# Generated by Django 5.2.4 on 2025-08-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_deleverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('CANCEL', 'Cancel'), ('SUCESS', 'Sucess'), ('UNSUCESS', 'Unsucess')], default='PENDING', max_length=20),
        ),
    ]
