# Generated by Django 5.2.4 on 2025-07-22 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=100)),
                ('kitchen_description', models.TextField(blank=True, null=True)),
                ('kitchen_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('kitchen_Types', models.CharField(default='hotel')),
                ('kitchen_profile_photo', models.FileField(upload_to='kitchens/profile_picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
