# Generated by Django 5.2.4 on 2025-08-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_registration_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistrationform',
            name='kitchen_qr_photo',
            field=models.FileField(blank=True, null=True, upload_to='kitchens/QRimages'),
        ),
    ]
