# Generated by Django 5.2.4 on 2025-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('manager', 'Manager'), ('afs', 'Applied_for_seller')], default='buyer', max_length=10),
        ),
    ]
